### ISSUE TITLE
Intermittent JavaScript Unit Test Failures

### ISSUE THREAD

**Issue by swissspidy** [google/web-stories-wp#9383]
## Task Description

Sometimes the JS unit tests fail after some time with the following error:

```
TypeError: Cannot read properties of null (reading 'createEvent')
    at Object.invokeGuardedCallbackDev (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/react-dom/cjs/react-dom.development.js:3905:26)
    at invokeGuardedCallback (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at flushPassiveEffectsImpl (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/react-dom/cjs/react-dom.development.js:23543:11)
    at unstable_runWithPriority (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at flushPassiveEffects (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/react-dom/cjs/react-dom.development.js:23447:14)
    at Object.<anonymous>.flushWork (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/react-dom/cjs/react-dom-test-utils.development.js:992:10)
    at Immediate.<anonymous> (/home/runner/work/web-stories-wp/web-stories-wp/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1003:11)
    at processImmediate (node:internal/timers:464:21)
```

Example run:

https://github.com/google/web-stories-wp/runs/3868035090?check_suite_focus=true

A quick Google search suggests that this might be due to some unmocked API call or missing `await` on some assertion

**Comment by swissspidy** [comment]
Feels like this has been happening less often recently.
